[package]
name = "daummap"
version = "0.1.0"
authors = ["pbzweihander <sd852456@naver.com>"]
description = "Daum Map API wrapper"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/daummap/"
repository = "https://github.com/pbzweihander/daummap-rs"
readme = "README.md"

[dependencies]
error-chain = "0.11"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
